introduction of non-adjustables
modded-factorio/bobsmods pull request #101
Opened 2022-12-26 21:50 UTC by AiDSl

fixes for non-adjustable inserter.
adjustables are not limited to all inserter with allow_custom_vector.
bob`s logistics still have all inserter as adjustables.

2022-12-26 23:44 UTC, KiwiHawk requested changes

2022-12-26 23:44 UTC, KiwiHawk commented on bobinserters/data-updates.lua
> +local enable_inserter=
Excluding inserters that don't `allow_custom_vectors` is good!
For everything else: I don't want to maintain an allow list for inserters. There are loads of mods that add inserters. By default, Adjustable Inserters should work with any of them.

Please remove `enable_inserters`.

2022-12-27 06:40 UTC, AiDSl commented on bobinserters/data-updates.lua
> +local enable_inserter=
k, instead of only handle things in list,new version only provide new option to skip the "make it adjustable" part of code.

2022-12-27 07:36 UTC, KiwiHawk commented on bobinserters/data-updates.lua
> +local enable_inserter=
There are already two way to prevent an inserter being adjustable. Do we really need to add a third? 🤔

1. In `data-final-fixes`, set `inserter.allow_custom_vectors = false`
2. In `control`, call remote interface

Remote example:
```lua
remote.call("bobinserters", "blacklist_inserters", { "burner-inserter" } )
```

2022-12-27 09:37 UTC, AiDSl commented on bobinserters/data-updates.lua
> +local enable_inserter=
yes we do,because there are 3 types of inserters actually:

1.non adjustable
2.non bob adjustable
3.adjustable

the (2)non bob adjustable can be from mod like side inserter,it is still mean to be a adjustable but not as freely as bob's did for balance reason.

the control.lua change is meant to prevent (1)non-adjustable or (2)non-bob-adjustable glitch shown incorrect adjustment gui

the data-updates.lua in other hand is mean to differentiate the (3)adjustable and (1)non-adjustable early,the old implementation just give a little troll to the inserter that dont meant to be adjusted in any case.

that is why called this pull request as "introduction of non adjustables",because it both prevent the non adjustables to be change in data phase if you set the property in current phase,and fixs the problem that inserter can shown wrong gui.

if you removed the check of allow_custom_vector in the control.lua,it would only fix the (2)non bob adjustable,the (1)non adjustable will still have bug that still show incorrect gui.

if you removed the new check in data-updates.lua,
it will turn all inserter into adjustable unconditionally,then any mod maker have to add a fix after the phase2 of bob's inserter which can be prevented in the data phase first place!

2022-12-27 09:46 UTC, AiDSl commented on bobinserters/data-updates.lua
> +local enable_inserter=
(1)non adjustable only need the modmaker add a property in their entity registration
(2)non bob adjustable only need to add blacklist
(3)adjustable still need no change in code

2022-12-27 11:08 UTC, KiwiHawk commented on bobinserters/data-updates.lua
> +local enable_inserter=
Yes, I understand all that. But that doesn't explain to me why we need `bobinserter_non_adjustable`. This is for number 2 on your list, right? The same thing can be achieved by setting `inserter.allow_custom_vectors = false` in `data-final-fixes` (or `data-updates` with Adjustable Inserters as a dependency).

2022-12-27 11:49 UTC, AiDSl commented on bobinserters/data-updates.lua
> +local enable_inserter=
you misunderstood, bobinserter_non_adjustable is meant to differentiate the (1)non adjustable and the (3)adjustable,there's not for number 2 in any way.

and as you mention it can be done with single line in phase 3,the fact is everything can be done in phase 3,we can register everything into phase 3,the point have mutiple phase is make modder dont need to do that.

imagine if dev make barreling unconditional and you are the guy try to prevent certain fluid(like energy) be put into barrel... it will just make everybody's life simplier by having it as a option in phase 1.

it maybe just 1 line of code,but where it is have big impact to everyone interact with it,I think this property is side by side wth stack and filter function,so I put that there just be part of inserter data.

2022-12-30 22:53 UTC, KiwiHawk commented on bobinserters/data-updates.lua
> +local enable_inserter=
Okay, that makes sense. Thanks for the explanation!

2022-12-30 22:54 UTC, KiwiHawk approved these changes

2023-01-01 05:52 UTC, merged