Updating Bob's Modules and preparing some ground work for quality modules
modded-factorio/bobsmods pull request #199
Opened 2024-10-23 14:59 UTC by Para0234

This is an update to Bob's Modules to be compatible with Factorio 2.0

I also decided to add quality bonuses to god modules, and in such a way that it can be reused for standard quality modules. However, the numbers may need to be tweaked.

Of course, I made sure to disable the quality bonus in case the player doesn't have the space age DLC.

I also changed the way "bobmods-modules-enableproductivitylimitation" (AKA the limitations on productivity) works, since 2.0 broke it, but it should be relatively invisible to the user.

I also added a new option to the mod, allowing beacons to transmit quality alongside productivity.

2024-10-23 15:04 UTC, Para0234 commented
Bob's Libraries was not modified at all during that test, so it appears to be working properly without needing changes.

2024-10-23 19:25 UTC, KiwiHawk requested changes

2024-10-23 19:25 UTC, KiwiHawk commented on bobmodules/data-updates.lua
> +    table.insert(beacon.allowed_effects, "quality")
Quality is added to beacons if either setting is enabled. Is this deliberate? If so, why?

2024-10-23 19:25 UTC, KiwiHawk commented on bobmodules/settings.lua
> +  },
Quality related settings should only be added if quality is enabled.

https://lua-api.factorio.com/latest/types/FeatureFlags.html#quality

2024-10-23 19:31 UTC, KiwiHawk commented
Thanks for starting on updating this mod!
I've added a couple of review comments based on a quick scan of your changes.

*However* I have been planning a major overhaul of this mod. To try address some of it's glaring issues.

1. It adds too many module tiers. There are multiple tiers that unlock with the same science packs. So there is no point using many tiers, you may as well skip and go directly to the higher tier.

2. It's far too powerful. This mod is known among modders to be stupidly broken OP! I'd like to try change that. At least with default settings. Otherwise with the ability to make Legendary Quality modules, it becomes even worse!

Fixing these issues will cause disruption. However I do believe that now is the best time for making breaking changes.

2024-10-23 19:46 UTC, Para0234 commented on bobmodules/settings.lua
> +  },
I won't be able to change that before at least 12 to 14 hours, but will do.

2024-10-23 19:47 UTC, Para0234 commented on bobmodules/data-updates.lua
> +    table.insert(beacon.allowed_effects, "quality")
Normally, the correction has been done. It was a mistake on my part, as my original plan was to make the "productivity in beacons", before I decided to make a whole new option for it. I, however, completely forgot to delete the original change.

2024-10-23 19:52 UTC, Para0234 commented
Honestly, I like the mod how it is. It's stupid OP, but well, it could be worse, honestly, but I understand the changes you want to take it to (Although, keeping the god modules as-is, AKA optional and powerful), would be absolutely perfect for me. Although, Bob's mods tend to always end up stupid OP when pushed to their limits, and that's how I like it.

If I may ask, do you already have plans on what you want to change? Maybe I can try to work on them.

2024-10-24 00:09 UTC, KiwiHawk commented
One module tier unlocked per tech tier. For vanilla this will be:
- Green
- Blue
- Purple
- Yellow
- Space

Not sure about with Space Age yet.

2024-10-24 07:23 UTC, Qatavin commented
Could do something like 5 tiers for the base game and 8 for Space Age (with something like 3 on Nauvis, and the remaining 5 elsewhere). However, I would say that science packs are not the only way to space out these tiers. Materials can also do it, such as how gems are the key to unlocking tier 5 currently - materials you might otherwise put off acquiring. Here's an example of how I've gone about it in my mod, as a listing of what is needed to advance to each level. It goes up one tier of electronics every odd level, and every even level has an added ingredient.

(Efficiency modules)
1: Red circuit board components, aluminium, gold to make module case and contacts, and chemical sci
2: Red circuit board components, solar panel (requires silver)
3: Blue circuit board components, production sci
4: Blue circuit board components, lithium ion battery(third tier of four in my mod)
5: Purple circuit board components, gems
6: Purple circuit board components, power electronics (requires gallium and indium to be set up)
7: Rocket control unit components (also requires gallium), utility sci
8: Rocket control unit components, radioisotope generator

Another benefit of taking this approach is that it makes modules more interesting than being just another electronics item. This was obviously inspired by how Space Exploration does it, but honestly I think Bob's has the potential to do it better, given the how many potential materials we have at our disposal. Personally, I would keep the number of tiers at 8, and I'm sure many people would be disappointed to see otherwise (though the default parameters should definitely come down _a lot_) but an alternative 5 tier arrangement could look like this:

1: Red circuit board components, aluminium, gold, chem sci
2: Blue circuit board components, gems
3; Blue circuit board components, prod sci
4: Purple circuit board components, lithium battery(etc)
5: Purple circuit board components, utility sci, radioisotope generator

2024-10-25 20:02 UTC, Para0234 commented
Both changes have now been made, and I tested the changes. As for the rework of the mod, it would probably take much longer, and well, maybe I can work on other factorio mods to update them instead. (This, plus I like the current form of bob's modules lmao)

2024-10-25 20:04 UTC, Para0234 commented on bobmodules/settings.lua
> +  },
Done

2024-11-01 22:25 UTC, Para0234 commented
Is it possible to do anything with this PR? Either pull or close, but well, something?

2024-11-05 21:20 UTC, KiwiHawk commented
> Is it possible to do anything with this PR? Either pull or close, but well, something?

Yes, I've got some time off work booked coming up. Have been busy sorry but I will get to it!

2024-12-02 10:35 UTC, Para0234 commented
Heya.

Any news?

2024-12-03 23:53 UTC, Para0234 commented on bobmodules/data-updates.lua
> +    table.insert(beacon.allowed_effects, "quality")
I was absolutly sure I made the change. I probably forgot to save last time...

Shame it took me two months to realize that.

2024-12-04 10:50 UTC, Para0234 commented
Before you commit, tell me if I need to lower the quality I added to the ultimate modules. It might be too high.

2024-12-30 06:05 UTC, Qatavin requested changes
This looks mostly good. I'm wondering about the beacons, though. By the looks of it, beacon_counter for all beacons is going to be "same_type", which if I understand the parameter correctly means that the three tiers of beacon will be counted separately for the effectiveness penalty for overlapping beacons, so you could build one of each tier and have any machine in range get full benefits from each of them. Seems janky and exploitable. Unless I'm mistaken, all beacons should have beacon_counter = "global" instead.

My other main concern is the cost of modules. Vanilla modules are the most expensive mass production items in the game. Bob's modules have always been extremely cheap in comparison. I mean, using replace_ingredient to replace processing units with integrated electronics 1-to-1? That's just not right. Increasing their cost when they use Bob's Electronics components seems like a must.

I also had a thought about gems. Not all types of modules have to use the same ones. You could do something like have productivity/quality modules use sapphire-amethyst-topaz-diamond while other types use ruby-emerald-topaz-diamond, to spread out the usage of gems types. Or alternatively, ruby-sapphire-amethyst-diamond and ruby-sapphire-emerald-topaz. Just something to consider.

2025-01-01 07:58 UTC, KiwiHawk commented
Most of @Qatavin 's feedback has been implemented. Modules are still cheap but not quite as extreme as previously.

2025-01-01 07:59 UTC, merged